version: '3'
services:
 db:
  image: mysql:latest
  ports:
   - "3386:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: 'rsvp'
   MYSQL_USER: 'root'
   MYSQL_ROOT_PASSWORD: 'root_password'
  volumes:
   - ./db:/docker-entrypoint-initdb.d/:ro
  networks:
   - rsvpnet

 web:
   build: . 
   ports:
    - "5000:5000"
   environment:
    TEXT1: Hackfest 
    TEXT2: Registration 
    ORGANIZER: UVCE
   depends_on: 
    - db 
   networks: 
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
